#!/usr/bin/env python3
"""Build self-contained skill packages from the shared review methodology."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILES = (
    ROOT / "src/core/workflow.md",
    ROOT / "src/core/review-criteria.md",
    ROOT / "src/core/output-contract.md",
)
TARGETS = {
    "codex": ROOT / "dist/codex/code-review/SKILL.md",
    "claude-code": ROOT / "dist/claude-code/code-review/SKILL.md",
}
FRONTMATTER = """---
name: code-review
description: Review code changes for actionable defects with evidence-based findings and controlled false positives. Use when asked to review a diff, commit, branch, pull request, or working tree.
---
"""
GENERATED_NOTICE = """
<!-- Generated by scripts/build.py. Do not edit this file directly. -->

# Code Review

Review the requested code change with the shared workflow below. Use the
repository's available file, search, diff, and test tools to gather evidence.
Do not modify the reviewed code unless the user separately asks for changes.
"""


def normalized_source(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    text = text.replace(
        "Apply the checks in [review-criteria.md](review-criteria.md) according to the",
        "Apply the checks in the Review Criteria section according to the",
    )
    text = text.replace(
        "Follow [output-contract.md](output-contract.md) for priority, finding content,",
        "Follow the Review Output Contract section for priority, finding content,",
    )
    return text


def render() -> str:
    sections = "\n\n---\n\n".join(normalized_source(path) for path in SOURCE_FILES)
    digest = hashlib.sha256(
        b"\0".join(path.read_bytes() for path in SOURCE_FILES)
    ).hexdigest()
    return (
        FRONTMATTER
        + GENERATED_NOTICE
        + f"\n<!-- source-sha256: {digest} -->\n\n"
        + sections
        + "\n"
    )


def write_outputs(content: str) -> None:
    for target in TARGETS.values():
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("w", encoding="utf-8", newline="\n") as output:
            output.write(content)


def check_outputs(content: str) -> list[str]:
    errors: list[str] = []
    for agent, target in TARGETS.items():
        if not target.exists():
            errors.append(f"missing generated package for {agent}: {target.relative_to(ROOT)}")
        elif target.read_text(encoding="utf-8") != content:
            errors.append(f"stale generated package for {agent}: {target.relative_to(ROOT)}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail when generated packages are stale"
    )
    args = parser.parse_args()
    content = render()
    if args.check:
        errors = check_outputs(content)
        if errors:
            print("\n".join(errors))
            return 1
        print("Generated skill packages are current.")
        return 0
    write_outputs(content)
    print("Generated skill packages for: " + ", ".join(TARGETS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
