#!/usr/bin/env python3
"""Build self-contained skill packages from the shared review methodology."""

from __future__ import annotations

import argparse
import hashlib
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILES = (
    ROOT / "src/core/workflow.md",
)
REFERENCE_FILES = {
    Path("references/review-criteria.md"): ROOT / "src/core/review-criteria.md",
    Path("references/multi-agent-decomposition.md"): ROOT
    / "src/core/multi-agent-decomposition.md",
    Path("references/output-contract.md"): ROOT / "src/core/output-contract.md",
    Path("references/communication-guidelines.md"): ROOT
    / "src/core/communication-guidelines.md",
    Path("references/technologies/README.md"): ROOT / "src/technologies/README.md",
    Path("references/technologies/README.ja.md"): ROOT
    / "src/technologies/README.ja.md",
}
TARGETS = {
    "codex": ROOT / "dist/codex/evidence-code-review/SKILL.md",
    "claude-code": ROOT / "dist/claude-code/evidence-code-review/SKILL.md",
}
FRONTMATTER = """---
name: evidence-code-review
description: Review code changes for actionable defects with evidence-based findings and controlled false positives. Use when asked to review a diff, commit, branch, pull request, or working tree, including when AGENTS.md, CLAUDE.md, or other repository instructions already describe how to review; the skill reads those instructions and applies them within its workflow.
---
"""
GENERATED_NOTICE = """
<!-- Generated by scripts/build.py. Do not edit this file directly. -->

# Code Review

Review the requested code change with the shared workflow below. Use the
repository's available file, search, diff, and test tools to gather evidence.
Do not modify the reviewed code unless the user separately asks for changes.
"""


def normalized_source(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    text = text.replace(
        "Apply the checks in [review-criteria.md](review-criteria.md) according to the",
        "Apply the checks in [the review criteria](references/review-criteria.md) according to the",
    )
    text = text.replace(
        "using [multi-agent decomposition](multi-agent-decomposition.md). It is",
        "using [multi-agent decomposition](references/multi-agent-decomposition.md). It is",
    )
    text = text.replace(
        "Follow [output-contract.md](output-contract.md) for action level, viewpoint,",
        "Follow [the output contract](references/output-contract.md) for action level, viewpoint,",
    )
    text = text.replace(
        "[communication-guidelines.md](communication-guidelines.md) before returning the",
        "[the communication guidelines](references/communication-guidelines.md) before returning the",
    )
    return text


def render() -> str:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    sections = "\n\n---\n\n".join(normalized_source(path) for path in SOURCE_FILES)
    digest = hashlib.sha256(
        b"\0".join(
            path.read_bytes() for path in (*SOURCE_FILES, *REFERENCE_FILES.values())
        )
    ).hexdigest()
    return (
        FRONTMATTER
        + GENERATED_NOTICE
        + f"\n<!-- skill-version: v{version} -->\n"
        + f"\n<!-- source-sha256: {digest} -->\n\n"
        + sections
        + "\n"
    )


def write_outputs(content: str) -> None:
    for target in TARGETS.values():
        if target.parent.exists():
            shutil.rmtree(target.parent)
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("w", encoding="utf-8", newline="\n") as output:
            output.write(content)
        for relative, source in REFERENCE_FILES.items():
            reference = target.parent / relative
            reference.parent.mkdir(parents=True, exist_ok=True)
            with reference.open("w", encoding="utf-8", newline="\n") as output:
                output.write(source.read_text(encoding="utf-8"))


def check_outputs(content: str) -> list[str]:
    errors: list[str] = []
    for agent, target in TARGETS.items():
        expected_files = {Path("SKILL.md"), *REFERENCE_FILES}
        if target.parent.exists():
            actual_files = {
                path.relative_to(target.parent)
                for path in target.parent.rglob("*")
                if path.is_file() or path.is_symlink()
            }
            for unexpected in sorted(actual_files - expected_files):
                errors.append(
                    "unexpected generated file for "
                    f"{agent}: {(target.parent / unexpected).relative_to(ROOT)}"
                )
        if not target.exists():
            errors.append(f"missing generated package for {agent}: {target.relative_to(ROOT)}")
        elif target.read_text(encoding="utf-8") != content:
            errors.append(f"stale generated package for {agent}: {target.relative_to(ROOT)}")
        for relative, source in REFERENCE_FILES.items():
            reference = target.parent / relative
            if not reference.exists():
                errors.append(
                    f"missing generated reference for {agent}: {reference.relative_to(ROOT)}"
                )
            elif reference.read_text(encoding="utf-8") != source.read_text(encoding="utf-8"):
                errors.append(
                    f"stale generated reference for {agent}: {reference.relative_to(ROOT)}"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail when generated packages are stale"
    )
    args = parser.parse_args()
    content = render()
    if args.check:
        errors = check_outputs(content)
        if errors:
            print("\n".join(errors))
            return 1
        print("Generated skill packages are current.")
        return 0
    write_outputs(content)
    print("Generated skill packages for: " + ", ".join(TARGETS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
